### PR TITLE
Fix DataFrame.rows with empty argument (#268)

### PR DESCRIPTION
**Pull request by zverok**

### CODE REVIEW

**Comment by v0dro** [comment]
Failing tests. Please make them pass and I'll merge.

**Comment by zverok** [comment]
Oh, there is Rubocop fails, will fix them tomorrow. On my way home from EuRuKo in Bulgaria, have seen Matz and even managed to give a lightning talk about SciRuby and related matters :)

**Comment by v0dro** [comment]
Do post the talk link on the mailing list when it is up!

**Comment by zverok** [comment]
OK, I've just rebased from current master and now everything should be OK with Rubocop too :)

> Do post the talk link on the mailing list when it is up!

To be honest, it was an epic fail :) I wanted to talk about just too much, and had not enough time (lightning talks was 5 min there), so... I think I've just failed. But not before stressing on several important points and praising SciRuby :)

**Pull request merged**
