### PR TITLE
Added #union method with test cases.

### PR DESCRIPTION
**Pull request by Emrys-Merlin**
Hi,

I tried to address issue #230 and added a union method to the DataFrame class.

I am unsure about how to handle indices containing common elements. So far I decided to raise an error. If you think, some other behavior would be bettter I can change that. Just let me know.

This is my first contribution to a major project, so if there is anything I should have done differently or some other mistake, please feel free to tell me.

Best regards
Tim

### CODE REVIEW

**Comment by v0dro** [comment]
Thanks for your contribution.

@gnilrets how do you think indices containing common elements should be handled?

**Comment by gnilrets** [comment]
@v0dro - Two options
1 - Whichever dataframe comes last wins.
2 - Create a multi-index that contains both records

1 would probably be pretty easy to handle.  I'd probably hold off on supporting 2 unless someone can come up with a valid use case.

**Comment by Emrys-Merlin** [comment]
Hi everyone,

I implemented the "last dataframe wins" approach. Locally, my test cases work fine.

I rebased to the latest master snapshot and now the checks seem to fail. However, if I understand the check logs correctly, the offenses seem to have nothing to do with the code I provided. Is there anything I should do to make the checks pass? Is there anything else I should be aware of?

Thanks in advance.

**Comment by lokeshh** [comment]
> I tried to rebas to the latest master snapshot and now the checks seem to fail. However, if I understand the check logs correctly, the offenses seem to have nothing to do with the code I provided. Is there anything I should do to make the checks pass? Is there anything else I should be aware of?

@Emrys-Merlin Its because the Rubocop got updated. Do `bundle update` and you will see the same failures when you run rubocop. @genya0407 have fixed those offences in https://github.com/v0dro/daru/pull/277 so no need to do the same work again.

**Comment by v0dro** [comment]
@Emrys-Merlin any update on this?

**Comment by Emrys-Merlin** [comment]
I was waiting for #277 to get merged, so that I do not have to refactor the code to conform with the new rubocop version, too, as @lokeshh mentioned in his post. Besides this point, I think the union method should be working.

**Comment by v0dro** [comment]
Has been done. https://github.com/v0dro/daru/pull/277/

**Comment by Emrys-Merlin** [comment]
Okay, then everything should be ready to go.

**Pull request merged**
