### PR TITLE
FIX - Vector sort now sorts nil at the beginning

### PR DESCRIPTION
**Pull request by gnilrets**

### CODE REVIEW

**Comment by gnilrets** [comment]
Resolves #39.  

So this fixes the issue but I'm not sure it's the best solution.  The problem is that if the user wanted to write their own sorter (by passing a block to sort), they'd still have to deal with the nil issue.  An alternative to the solution in this commit might be to add refinements to many of the core classes (NilClass, Fixnum, Float, etc) that allowed them to be sortable when nils are involved.  

````ruby
class NilClass
  include Comparable
  def <=>(other)
    return 0 if other.nil?
    -1
  end
end
````

That, of course, comes with its own set of issues.  Any thought on this?

**Comment by gnilrets** [comment]
Also, it looks like my editor is removing trailing whitespace (which is good according to https://github.com/bbatsov/ruby-style-guide#no-trailing-whitespace).

**Comment by v0dro** [comment]
Good fix. My only concern is speed. Will this slow things down significantly? The problem is that rewriting sorting in Ruby is slow as it is. The `if` conditions should not slow it down further.

**Comment by gnilrets** [comment]
This commit should slightly reduce the number of evaluations that need to happen when your data doesn't have many nils.  Not sure if we can do much better.

**Comment by v0dro** [comment]
This will work for now. Thanks. Merging.

**Pull request merged**
