### PR TITLE
Resolve conflict with narray

### LINKED ISSUE #27: conflict with NArray's NMatrix
Hi @v0dro 

Thank you for your great gem!
But daru conflict with Tanaka's NArray. 
```
 Error:  /narray-0.6.1.1/nmatrix.rb:8:in `<top (required)>': uninitialized constant NArray (NameError)
```
daru.rb
```
lib_underscore = library.to_s.gsub(/-/, '\_').gsub('/', '\_')
create_has_library :'nmatrix/nmatrix'
```
daru/accessors/nmatrix_wrapper.rb
```
end if Daru.has_nmatrix_nmatrix?
```
This work. But not cool.

### PR DESCRIPTION
**Pull request by lokeshh**
Fixes #27 

@v0dro Not sure but is this what you meant?

### CODE REVIEW

**Comment by v0dro** [comment]
Why is the build failing? Can you investigate?

**Comment by lokeshh** [comment]
Seems like they [removed obsolete `Prime.new` in Ruby 2.3](https://github.com/ruby/ruby/blob/v2_3_0/ChangeLog#L8423) and [this line](https://github.com/marcandre/backports/blob/54941c9203a6694f4c21141572e1d1c8f8dc38ac/lib/backports/1.9.1/stdlib/prime.rb#L84) returns `False` now.

**Comment by lokeshh** [comment]
The problem is that [this code](https://github.com/marcandre/backports/blob/54941c9203a6694f4c21141572e1d1c8f8dc38ac/lib/backports/1.9.1/stdlib/prime.rb#L83) from backports library fails to over write the class Prime. 

I tried running `Object.send(:remove_const, :Prime)` before [this line](https://github.com/marcandre/backports/blob/54941c9203a6694f4c21141572e1d1c8f8dc38ac/lib/backports/1.9.1/stdlib/prime.rb#L83) and it seems to work!

**Comment by v0dro** [comment]
Wow great :\

Could you the following code somewhere in `daru.rb`?

``` ruby

if RUBY_VERSION > "2.3.0"
  Object.send(:remove_const, :Prime)
end
```

I think that should fix it.

**Comment by lokeshh** [comment]
The backports library just got updated. The bug doesn't seem to be there anymore.

**Pull request merged**
