### PR TITLE
Filtering out 'vendor' from coverage targets

### PR DESCRIPTION
**Pull request by yui-knk**

### CODE REVIEW

**Comment by v0dro** [comment]
What does this change do exactly?

**Comment by yui-knk** [comment]
I first `bundle install --path vendor/bundle`. And then I run tests locally.
In this situation, before this commit, simplecov also calculates coverages for files
which are located under `vendor/bundle`.



This commit prevent simplecov calculating to coverages for files located under `vendor/bundle`.

**Comment by zverok** [comment]
@v0dro I think I can understand it. In some Bunlder _global_ settings, it creates local gem cache in _current_ project, and it is in `./vendor/bundle` folder. (I have this setting some time ago, it is somewhat convenient, but creates unexpected complications sometimes, like described above)

**Comment by v0dro** [comment]
Ok works.

**Pull request merged**
